version: '3'

services:
  # Container BE
  backend:
    build:
      context: ./BE/
      dockerfile: Dockerfile
    restart: unless-stopped
    tty: true
    ports:
      - "3000:3000"  # Port mà ứng dụng backend chạy
    volumes:
      - backend-cache:/code/target
    networks:
      app-network:
        ipv4_address: 172.18.0.4

  # Container Database
  database:
    image: postgres:latest
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - "5432:5432"  # Port mà PostgreSQL chạy
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=iShop
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      app-network:
        ipv4_address: 172.18.0.3

  # Container pgAdmin
  pgadmin:
    image: dpage/pgadmin4
    restart: unless-stopped
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: mypgadminpass
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - database
    networks:
      app-network: null 

  # Container FE
  frontend:
    build:
      context: ./FE/
      dockerfile: Dockerfile
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"  
    depends_on:
      - database 
    networks:
      app-network:
        ipv4_address: 172.18.0.5 

# Docker Networks
networks:
  app-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16

volumes:
  backend-cache: {}
  db-data: {}
  pgadmin_data: {}